"""Initial migration

Revision ID: c4fc3a468ec0
Revises: 
Create Date: 2025-11-17 07:24:12.867032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text as sa_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4fc3a468ec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    userrole_enum = postgresql.ENUM(
        'ADMIN', 'MODERATOR', 'MEMBER',
        name='userrole',
        create_type=False,
    )
    promptstatus_enum = postgresql.ENUM(
        'DRAFT', 'PUBLISHED', 'ARCHIVED',
        name='promptstatus',
        create_type=False,
    )
    platformtag_enum = postgresql.ENUM(
        'GITHUB_COPILOT', 'O365_COPILOT', 'CURSOR', 'CLAUDE',
        name='platformtag',
        create_type=False,
    )

    # Create enum types for PostgreSQL (only if they don't exist)
    # Use IF NOT EXISTS pattern via DO block
    conn = op.get_bind()
    
    conn.execute(sa_text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
                CREATE TYPE userrole AS ENUM ('ADMIN', 'MODERATOR', 'MEMBER');
            END IF;
        END $$;
    """))
    conn.execute(sa_text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promptstatus') THEN
                CREATE TYPE promptstatus AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
            END IF;
        END $$;
    """))
    conn.execute(sa_text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'platformtag') THEN
                CREATE TYPE platformtag AS ENUM ('GITHUB_COPILOT', 'O365_COPILOT', 'CURSOR', 'CLAUDE');
            END IF;
        END $$;
    """))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', userrole_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform_tags', postgresql.ARRAY(platformtag_enum), nullable=False),
    sa.Column('use_cases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('usage_tips', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', promptstatus_enum, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_title'), 'prompts', ['title'], unique=False)
    op.create_table('prompt_categories',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('prompt_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_categories')
    op.drop_index(op.f('ix_prompts_title'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS platformtag")
    op.execute("DROP TYPE IF EXISTS promptstatus")
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
